$("#all-cards-slider").slick({
  infinite: !0,
  slidesToShow: 8,
  slidesToScroll: 1,
  autoplay: !0,
  dots: !1,
  arrows: !0,
  arrows: !0,
  speed: 1e3,
  loop: !0,
  adaptiveHeight: !0,
  variableWidth: !0,
  centerMode: !1,
  responsive: [
    {
      breakpoint: 1400,
      settings: { slidesToShow: 4, slidesToScroll: 4 },
    },
    { breakpoint: 990, settings: { slidesToShow: 3, slidesToScroll: 1 } },
    { breakpoint: 480, settings: { slidesToShow: 1, slidesToScroll: 1 } },
  ],
  prevArrow: "#all-cards-slider-prev-btn",
  nextArrow: "#all-cards-slider-next-btn",
}),
  $(".bny-gift-cards-sliders").length &&
    $(".bny-gift-cards-sliders").each(function () {
      var o = $(this).attr("id");
      $("#" + o).slick({
        infinite: !1,
        slidesToShow: 4,
        slidesToScroll: 2,
        autoplay: !1,
        dots: !0,
        arrows: !1,
        arrows: !1,
        speed: 1e3,
        loop: !0,
        adaptiveHeight: !1,
        responsive: [
          {
            breakpoint: 1400,
            settings: { slidesToShow: 4, slidesToScroll: 4 },
          },
          { breakpoint: 990, settings: { slidesToShow: 3, slidesToScroll: 1 } },
          { breakpoint: 600, settings: { slidesToShow: 2, slidesToScroll: 1 } },
          // { breakpoint: 380, settings: { slidesToShow: , slidesToScroll: 1 } },
        ],
      });
    }),
  $("#fav-cards-slider").slick({
    infinite: !1,
    slidesToShow: 4,
    slidesToScroll: 1,
    autoplay: !0,
    dots: !1,
    arrows: !0,
    arrows: !0,
    speed: 1e3,
    loop: !0,
    adaptiveHeight: !1,
    centerMode: !1,
    responsive: [
      {
        breakpoint: 1400,
        settings: { slidesToShow: 4, slidesToScroll: 4 },
      },
      { breakpoint: 990, settings: { slidesToShow: 3, slidesToScroll: 1 } },
      { breakpoint: 600, settings: { slidesToShow: 1, slidesToScroll: 1 } },
    ],
    prevArrow: "#fav-cards-slider-prev-btn",
    nextArrow: "#fav-cards-slider-next-btn",
  }),
  $("#fav-gift-slider").slick({
    infinite: !1,
    slidesToShow: 5,
    slidesToScroll: 1,
    autoplay: !0,
    dots: !1,
    arrows: !0,
    arrows: !0,
    speed: 1e3,
    loop: !0,
    adaptiveHeight: !1,
    centerMode: !1,
    responsive: [
      {
        breakpoint: 1400,
        settings: { slidesToShow: 4, slidesToScroll: 4 },
      },
      { breakpoint: 990, settings: { slidesToShow: 3, slidesToScroll: 1 } },
      { breakpoint: 600, settings: "unslick" },
    ],
    prevArrow: "#fav-gift-slider-prev-btn",
    nextArrow: "#fav-gift-slider-next-btn",
  }),
  $("#fav-gift-basket-slider").slick({
    infinite: !1,
    slidesToShow: 4,
    slidesToScroll: 1,
    autoplay: !0,
    dots: !1,
    arrows: !0,
    arrows: !0,
    speed: 1e3,
    loop: !0,
    adaptiveHeight: !1,
    centerMode: !1,
    responsive: [
      {
        breakpoint: 1400,
        settings: { slidesToShow: 4, slidesToScroll: 4 },
      },
      { breakpoint: 990, settings: { slidesToShow: 3, slidesToScroll: 1 } },
      { breakpoint: 600, settings: "unslick" },
    ],
    prevArrow: "#fav-gift-basket-slider-prev-btn",
    nextArrow: "#fav-gift-basket-slider-next-btn",
  }),
  $("#fav-gift-box-slider").slick({
    infinite: !1,
    slidesToShow: 4,
    slidesToScroll: 1,
    autoplay: !0,
    dots: !0,
    arrows: !0,
    arrows: !0,
    speed: 1e3,
    loop: !0,
    adaptiveHeight: !1,
    centerMode: !1,
    responsive: [
      {
        breakpoint: 1400,
        settings: { slidesToShow: 4, slidesToScroll: 4 },
      },
      { breakpoint: 990, settings: { slidesToShow: 2.5, slidesToScroll: 1 } },
      { breakpoint: 600, settings: { slidesToShow: 1.5, slidesToScroll: 1 } },
    ],
    prevArrow: "#fav-gift-box-slider-prev-btn",
    nextArrow: "#fav-gift-box-slider-next-btn",
  });